name: PowerShell Lint
on:
  push:
    paths: ["scripts/**/*.ps1"]
  pull_request:
    paths: ["scripts/**/*.ps1"]
  workflow_dispatch: {}  

jobs:
  analyze:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer
        run: Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
        shell: pwsh
      - name: Run analysis
        run: Invoke-ScriptAnalyzer -Path ./scripts -Recurse
        shell: pwsh
